using UnityEngine;

// 쮊 쫔콜쟙퀉
public class Bullet : MonoBehaviour
{
    [SerializeField] private float bulletSpeed;   // 쮊 쩁옷
    public int damage;                            // 쮊 온좗쵔

    public Transform target;                      // 점킨 콪썣

    Rigidbody2D rb;

    private void Awake()
    {
        rb = GetComponent<Rigidbody2D>();
    }
    private void Start()
    {
        rb.linearVelocity = transform.up * bulletSpeed;
    }
    private void OnTriggerEnter2D(Collider2D collision)
    {
        if (target != null && collision.transform != target) return;

        Destroy(gameObject);
    }
}
